name: UpdateAzureDevOpsRepo 1

on:
  push:
    branches: [ main ]

  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:       
        node-version: '16'
        cache: npm
    - name: Push to Azure DevOps
      uses: actions/github-script@v4
      with:
        script: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add azure "https://ZeroDay247@dev.azure.com/ZeroDay247/DeliveryTools_A1/_git/DeliveryTools_A1"
          git push azure main
