name: Azure
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: action/git@v0.2.0
      with:
        git_username: ${{ secrets.GIT_USERNAME }}
        git_password: ${{ secrets.GIT_PASSWORD }}
        git_email: ${{ secrets.GIT_EMAIL }}
        git_push_force: true
        git_remote_url: 'https://ZeroDay247@dev.azure.com/ZeroDay247/DeliveryTools_A1/_git/DeliveryTools_A1'