name: Update Azure DevOps Repo

on: [push]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure DevOps
      run: az devops login --organization https://dev.azure.com/ZeroDay247 --token ${{ secrets.AZURE_DEVOPS_USER_PAT }}
    - name: Import code
      run: |
        az repos create --name DeliveryTools_A1 --project DeliveryTools_A1 --detect true
        az repos import create --git-url https://github.com/TimLopesDevOps/DeliveryTools_A1.git --project DeliveryTools_A1 --repository DeliveryTools_A1 --detect true


    