name: Update Azure DevOps Repo

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to Azure DevOps
      uses: actions/checkout@v2
      with:
        azure_devops_user_email: ${{ secrets.AZURE_DEVOPS_USER_EMAIL }}
        azure_devops_user_pat: ${{ secrets.AZURE_DEVOPS_USER_PAT }}
        git_push_force: true
        git_remote_url: 'https://ZeroDay247@dev.azure.com/ZeroDay247/DeliveryTools_A1/_git/DeliveryTools_A1'

  run_command:
    runs-on: ubuntu-latest
    steps:
      - name: run echo command
        run: echo "hello world"
      - name: run multiple commands
        run: |
         echo "hello world "
         echo "This is Tim"